type: reference-docs
definitionId: products
settings:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: JavaScript
      - lang: Node.js
      - lang: Python
      - lang: Go
      - lang: C#
